# Generated by Django 5.1.3 on 2024-11-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0003_discussion_timetable'),
        ('teacherportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('students', models.ManyToManyField(related_name='teachers', to='studentportal.student')),
            ],
        ),
    ]
