# Generated by Django 5.1.3 on 2024-11-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherportal', '0003_remove_teacher_name_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
