# Generated by Django 5.1.3 on 2024-11-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentportal", "0003_discussion_timetable"),
        ("teacherportal", "0004_teacher_date_of_birth_teacher_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="remarks",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
    ]
