# Generated by Django 5.1.3 on 2024-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0004_attendance'),
        ('teacherportal', '0009_marks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'ordering': ['-date_awarded']},
        ),
        migrations.AlterField(
            model_name='marks',
            name='date_awarded',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('teacher', 'student', 'date_awarded')},
        ),
    ]
